name:                BecomingFunctional-hs
version:             0.1.0.0
license:             BSD3
license-file:        LICENSE
author:              dnlkrgr
maintainer:          danielkrueger@protonmail.com

ghc-options: -Wall

dependencies:
 - base

library:
  source-dirs: Data

tests:
  spec:
    defaults: hspec/hspec@master
    dependencies: BecomingFunctional-hs
